server:
  port: 8060

spring:
  application:
    name: weather-reporter
  datasource:
    url: jdbc:postgresql://localhost:5432/weather
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    show-sql: true
    open-in-view: false
  cache:
    type: redis
    redis:
      time-to-live: 300000
  data:
    redis:
      host: localhost
      port: 6379
      password: admin

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

integration:
  openweather:
    units: metric

security:
  username: admin
  password: admin
  jwt:
    secret-key: c2VjcmV0S2V5c2VjcmV0S2V5c2VjcmV0S2V5c2VjcmV0S2V5

logging:
  level:
    root: debug