server:
  name: kibana
  host: 0.0.0.0
  publicBaseUrl: http://localhost:5601

monitoring:
  ui:
    container:
      elasticsearch:
        enabled: true

elasticsearch:
  hosts:
    - http://elasticsearch:9200